name: publish
on: [push]
jobs:
publish-cdxgen-docker-image:
runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v2
  - name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
  - name: Build the cdxgen Docker image
run: |
  docker build . --tag ghcr.io/dorjecurreli/cdxgen:latest
  docker run ghcr.io/dorjecurreli/cdxgen:latest
  docker push ghcr.io/dorjecurreli/cdxgen:latest